apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cpu
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cpu
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
